### ISSUE TITLE
Move away from .lesshintrc

### ISSUE THREAD

**Issue by kokarn** [lesshint/lesshint#103]
ESLint have started to move away from `.eslintrc` in favor of `.eslintrc.json`, `.eslintrc.js` and `.eslintrc.yml` files.
It's described here [ESLint 1.10.0 new config file types](http://eslint.org/blog/2015/11/eslint-v1.10.0-released/#configuration-file-formats) and it makes a lot of sense.

I think we should do the same. 
Perhaps just `.json` for consistency?

Another thought, what are the actual benefits of having dot prefix? 
It seems to be a hassle to me because it's hidden on filesystems and stuff like that and no other benefit than "other linters do it".

**Comment by shellscape** [comment]
It's not just linters that have an 'rc' file. It's a long-standing industry standard practice.

https://en.wikipedia.org/wiki/Configuration_file#UNIX.2FLinux
http://stackoverflow.com/questions/11030552/what-does-rc-mean-in-dot-files
http://unix.stackexchange.com/questions/3467/what-does-rc-in-bashrc-stand-for

Hell, even Windows follows the same mantra: https://msdn.microsoft.com/en-us/library/windows/desktop/aa380599(v=vs.85).aspx, though you won't find dotfiles very often further back than Win7, though MS has begun to embrace them since tools like Git are now pervasive cross-platform, and VS has openly embraced compatibility with such tools.

Best answer I've seen on why to use dotfiles - http://askubuntu.com/a/94786

My vote is :-1: for changing to a .json extension and/or moving away from a dotfile for this one.

**Comment by kokarn** [comment]
Ah, yeah that explains it a bunch more. But you are opposed to move to a
.lesshintrc.json as well, correct?

**Comment by shellscape** [comment]
I really don't think it's needed, and would count only as cruft. If someone can't grok that the content of the rc file is json, they have bigger issues. :)

**Comment by jwilsson** [comment]
I'm with @shellscape on this one and I also think that the "other linters do it" argument is quite strong in favor of keeping it the same as today. Then people will be familiar with it.

**Comment by kokarn** [comment]
Sure thing, the majority have spoken!
