### ISSUE TITLE
finalNewline reports wrong line number

### ISSUE THREAD

**Issue by tkazec** [lesshint/lesshint#123]
```
Warning: app.less: line 228, col 24, zeroUnit: Unit should not be omitted on zero values.
Warning: app.less: line 277, finalNewline: Files should end with a newline.
Warning: app.less: line 293, col 13, zeroUnit: Unit should not be omitted on zero values.
```

**Comment by shellscape** [comment]
@tkazec please include the less you're seeing these errors on so we can accurately reproduce. :)

**Comment by adam-lynch** [comment]
:+1: 

```less
@import "something";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";
@import "something-else";

// should be last
@import "shame";

```

My file is 61 lines long but it's reporting line 14. I don't see why it's giving me this error anyway... I have a newline at the end?

**Comment by jwilsson** [comment]
Thanks @adam-lynch, I'm able to reproduce it. 

The problem is this: 
Right now, we naively use the length of the array that contains the root `stylesheet` node's children as the final line (which of course is incorrect) so that's why it shows the line number as something that's way below the total number of lines. I'll take a look at it.

**Comment by adam-lynch** [comment]
:+1:
