### ISSUE TITLE
trailingWhitespace option to ignore whitespace in comment blocks

### ISSUE THREAD

**Issue by ultraq** [lesshint/lesshint#172]
Hi, what do you think about adding an option for the trailingWhitespace linter to ignore trailing whitespace in comment blocks?  I often use them when writing documentation blocks to keep the left "margin" in line, and double-spaces for GitHub-flavoured markdown to allow for line breaks.

eg:

```javascript
/**
 * A comment.
 * 
 * Some other comment.  The line right above this one has a space after the *
 * to keep the left margin in line.
 * 
 * Some item on a single line  
 * This line will be separated from the above by a line break, instead
 * of being interpreted as part of the same paragraph when generating
 * docs using GitHub-flavoured markdown.
 */
```

**Comment by shellscape** [comment]
I don't quite understand why you need a space following the *, at the end of a line, to keep margins in line. Could you elaborate some more?

**Comment by ultraq** [comment]
It's probably just a stylistic thing which I've inherited given that the IDEs I use (Eclipse, IntelliJ IDEA and that family of products) all produce that single space as I press <Enter> on a new line within a comment block, and so those whitespaces are just everywhere in the comment blocks for front end code I've written since then.

Those IDEs can be set to strip trailing whitespace off code lines, but leave comment blocks like that well enough alone.

**Comment by shellscape** [comment]
We're in kind of a pickle with comments right now, due to one tiny limitation of PostCSS and how it handles whitespace. It's such a tiny issue, that it's not going to be resolved until their next major version. Because of that, we're just iterating through lines in the file to check the last character. It's not ideal, but it works. And as such, we can't really tell what kind of a block we're in when there's a trailing whitespace. Unfortunately right now, you'll have to setup your editor to trim that whitespace (that's what I've been doing with sublime and atom). I've got a note in the code for the trailingWhitespace linter to take another look at it when PostCSS gets an update.

**Comment by ultraq** [comment]
Cool cool, thanks for letting me know 👍
