### ISSUE TITLE
Available options/default value for qualifyingElement

### ISSUE THREAD

**Issue by jwilsson** [lesshint/lesshint#30]
Do we need any more options? Are we satisfied with the current default value? Any other thoughts?

Current options:
1. allowWithId (default `false`)
2. allowWithClass (default `false`)
3. allowWithAttribute (default `false`)

Please cast a vote for one of the options or post your other thoughts or suggestions for options.

**Comment by kokarn** [comment]
Is it possible to set this value to ```false``` to disallow them all? I know that it's default behaviour but people might want that in their config for clarity.

**Comment by jwilsson** [comment]
I'm not quite sure I know what you mean. Setting the whole `qualifyingElement` property to `false` will disable it (like all the others). I think we need to keep the options separately.

**Comment by kokarn** [comment]
So if i want to specify this in my config I have to write it all out?
```js
qualifyingElement: {
  allowWithId: false,
  allowWithClass: false,
  allowWithAttribute: false
}

I guess it makes more sense to disable it all with false, you are right. You can close this if you want.

**Comment by CITguy** [comment]
I would agree that it would make the most sense disabling all three options by default and have devs explicitly enable the options they want.  However, is there a possibility to update the linter so that the option will default to false if not present?  This way, as a developer, I could configure this linter as follows:

Example: ID Only
```javascript
qualifyingElement: {
  allowWithId: true
}
```
_`allowWithClass` and `allowWithAttribute` are not present, so the linter defaults those options to `false`_

**Comment by kokarn** [comment]
I think that's how it works today. If @jwilsson can just confirm we can close this as resolved :)

**Comment by jwilsson** [comment]
Yep, this is exactly how it works today. All the options are `false` by default and can be enabled separately.
