### ISSUE TITLE
Using custom linters via the CLI

### ISSUE THREAD

**Issue by kloots** [lesshint/lesshint#325]
[The README indicates custom linters can be defined via the CLI](https://github.com/lesshint/lesshint#cli-usage) via the `--linters` option, however, from my experience adding custom linters to the `lesshintrc` file they must also be enabled. Can you provide an example of custom linter usage via the CLI as it is unclear how to both define and enable the customer linter via the CLI.

Thanks.

**Comment by jwilsson** [comment]
We have a big round of documentation changes coming up, I'll be sure to add it there. Thanks for pointing it out!

**Comment by kloots** [comment]
Great to hear the docs will be getting more robust. In the meantime, can you give me some guidance on defining and enabling custom linters via the CLI in this ticket so I can move forward?

**Comment by jwilsson** [comment]
Sure thing!


```bash
lesshint --linters=/path/to/linter.js file.less
```

This should work, given that the linters are enabled in your config. I think @JoshuaKGoldberg might be better suited to answer any questions though, since he wrote that part (I'm not familiar with it, unfortunately).

**Comment by JoshuaKGoldberg** [comment]
Hi, yes! It "should"**&#42;** be a relatively simple process. Something like following should probably end up in the docs in some form...

First, create a JavaScript file somewhere that looks like one of the linters from lesshint's [`lib/linters`](https://github.com/lesshint/lesshint/tree/6cbb82e37e2128bbed20db991de47142a4bf2f8f/lib/linters) directory. [`important_rule.js`](https://github.com/lesshint/lesshint/blob/6cbb82e37e2128bbed20db991de47142a4bf2f8f/lib/linters/important_rule.js) is a pretty simple starting point.

As a custom example, here's a rule that logs on every declaration:

```javascript
// verbose_rule.js
'use strict';

console.log('Loaded verbose_rule.js.');

module.exports = {
    name: 'verbose',
    nodeTypes: ['decl'],

    lint: function verboseLinter(config, node) {
        console.log('Found node setting', node.prop, 'to', node.value);
    }
};
```

Given the following file named `test.less`...

```less
.foo {
    color: bar;
}
```

...and a `.lesshintrc` file that enables the rule...

```json
{
    "verbose": true
}
```

...if you run the following command&#42; (assuming you've run `npm i -g lesshint`)...

```cmd
lesshint test.less --linters C:/Code/lesshint-testing/verbose_rule.js
```

...you should get the following output:

```cmd
Loaded verbose_rule.js.
Found node setting color to bar
```

You can then extend the linter to return an array of failures. 

&#42;After testing v2.4.0 today, it looks like the `require` logic requires relative to the `lesshint` install, *not* the script calling it. I'll fix that ASAP. You can get around it by using the absolute paths (`C:/Code/my-lesshint-stuff/linter.js` instead of `./linter.js`). As per [this SO answer](http://stackoverflow.com/questions/21056748/seriously-debugging-node-js-cannot-find-module-xyz-abcd) you can debug where Node is looking for objects via `require`. `export NODE_DEBUG=module` on *nix; `set NODE_DEBUG=module` on Windows.

**Comment by jwilsson** [comment]
Closing this since it's better documented now.

@kloots Please give us a shout if you disagree!
