### ISSUE TITLE
Improve CLI usage

### ISSUE THREAD

**Issue by kokarn** [lesshint/lesshint#357]
This is a placeholder for things I'd like to see implemented for the CLI.

* ```-v``` option to output a helping text that says "maybe you meant ```-V``` or ```--version```"
* Message when no files are found
* Something when just running ```lesshint```
* Allow glob patterns for files and/or folders

**Comment by shellscape** [comment]
`globby` for the last one. best glob module I've used

**Comment by jwilsson** [comment]
> -v option to output current version

We got `-V` and `--version` which is automatically supplied by `commander.js`. I also think we should save `-v` for a future `--verbose`.

> Message when no files are found

Do you mean when `lesshint foo/` is run and `foo/` is empty, it should print something? If so, agreed.

> Something when just running `lesshint`

This has worked before, I think we broke it in `3.0`.

> Allow glob patterns for files and/or folders

Agreed. It looks like we can replace `minimatch` (which we're currently using) with `globby` since `globby` wraps `glob` which uses `minimatch`. I'll do some further investigations.

**Comment by jwilsson** [comment]
My bad, `globby` and `minimatch` does different things (of course). I say we use `globby` too.

**Comment by kokarn** [comment]
Updated suggestion, until we get ```-v``` a helping text that says "maybe you ment ```-V```" would be nice

**Comment by jwilsson** [comment]
I'm going to close this.

Point 3 and 4 are fixed and released.
Point 1 can't be solved in a nice way using `commander.js` and without adding a new flag.
Point 2 can't be really be solved either because there's really no way for us to know if there weren't any files found at all or just no linting errors in the files found.
