### ISSUE TITLE
Lesshint outputs wrong line number

### ISSUE THREAD

**Issue by dishad** [lesshint/lesshint#40]
Following test was done in v0.7.0

```
h1 {
  width: 100px;
  height: 100px;
  color: #00f;
  background: #000;
  top:10px;
  left: 1000px;
}
```

This example Less/CSS file only has the rule `finalNewline` disabled and it reports the following errors:
```test.less: line 7, col 10, hexLength: #00f should be written in the long-form format.```
```test.less: line 9, col 15, hexLength: #000 should be written in the long-form format.```
```test.less: line 11, col 7, spaceAfterPropertyColon: Colon after property name should be followed by one space.```

As you can see the errors are not correctly guiding me to the correct line number.

Thanks

**Comment by jwilsson** [comment]
Thanks for the report!

I've managed to track the problem down to the use of Windows line endings (`\r\n`) instead of Unix ones (`\n`).

The real issue seems to lie in our Less parser, [gonzales-pe](https://github.com/tonyganch/gonzales-pe), but I'll add a workaround in our end (we'll probably need it somewhere else).

**Comment by jwilsson** [comment]
This should be fixed in `0.7.1`. 

Let me know if the issue still persists!

**Comment by dishad** [comment]
Thanks and will do!

**Comment by dishad** [comment]
The issue is no more! Great job.
