### ISSUE TITLE
Request: options for enforcing alphabetized property names/order

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#41]
We use/encourage alphabetizing our property names within our org. Would be great to make this an option.

**Comment by kokarn** [comment]
Hello! Great to see lesshint being used :)

I seem to recall something with ```border-color``` before ```border-width``` or something like that breaking when doing alphabetical, that's not something you've encountered?

How do you handle overwrites and stuff like that? Just curious on how strict this should be :)

**Comment by jwilsson** [comment]
I don't think we need to be that advanced and handle overwrites.

I think it's enough to just gather all the properties in the ruleset and just run a regular [`sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) on it (optionally with a [`localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) check for a bit more intelligence but that shouldn't be needed since it's always English. Perhaps just some logic to handle lower and upper case letters since `sort()` just checks Unicode points which will cause "C" to come before "b") and then compare it against the order that the properties are written in the ruleset.

Any mismatch between these two lists equals an error.
