### ISSUE TITLE
Forking and contributing

### ISSUE THREAD

**Issue by shellscape** [lesshint/lesshint#45]
We've decided to move forward with forking lesshint and contributing to it, but wanted to get on the same page with how you guys are using branches.

It appears from the request to PR to the 0.8.1 branch, that you're developing off of separate branches before pushing to master. So that's our first question - Why? Typically branches like that are used for features and then PR'd to master. Or a branch is marked as 'development' and used by primary maintainers/contributors to do out-of-track-next-major-version work. But PRs from forks are almost always made to master. 

It also looks like you're creating a branch to work on a patch release, which is not something we've seen done before. We've seen minor and major branches before, but never for a patch release (as following semver, patch releases are for bugfixes only and should follow the primary track).

We follow semver pretty closely in our org, and for ease of use and org-wide contribution, it'd be great to get on the same page. I'm certainly not suggesting that you adopt any of our practices, merely requesting some discussion around adopting some more widely accepted standards in this area.

**Comment by kokarn** [comment]
Great news! Good to see somebody else finding this as useful as we are.

I haven't contributed to the main lesshint lib yet, but mainly to the grunt-lesshint plugin. That one uses a git-flow like system for branching. Maybe that could be a good way to work with this if @jwilsson doesn't have any specific reasoning for his branching system? ;)

https://github.com/lesshint/grunt-lesshint

**Comment by jwilsson** [comment]
Glad to hear you guys are liking it! :)

There's never been any specific reasoning behind the branches other than some sort of "master should always be deployable" and therefore `master` was kept in a stable state between versions. I haven't put that much thought into it, just kept on working for fun :) 

But now, since you guys are coming along and there seems to be more and more users it's probably time to decide on these sort of things. And since most people will probably use the published packages on npm I think we can safely keep `master` in a development state and pulling in changes from feature branches and keep development of major changes in a `develop` branch.

**Comment by shellscape** [comment]
:+1: I'd also look into tagging SHAs for particular released versions. That'll give anyone interested a way to view a snapshot of the stable code for a particular release.

**Comment by jwilsson** [comment]
You mean like the regular Git tags over at https://github.com/lesshint/lesshint/releases?

**Comment by shellscape** [comment]
Ooo I haven't used releases yet @jwilsson. Tags was the old school way, looks like releases takes care of that.

**Comment by jwilsson** [comment]
Yeah, tags and releases are pretty much the same thing. Releases is just GitHub's way to let you add notes and zip files.

All those releases were simply created with a regular `git tag X` and then pushed.

**Comment by jwilsson** [comment]
I think we've reached consensus on how to handle branches. Do all work on feature branches and then merge them into master. 

I'm therefore closing this.
