### ISSUE TITLE
PropertyNaming support

### ISSUE THREAD

**Issue by xavierfoucrier** [lesshint/lesshint#462]
Add the ability to support `PropertyNaming` setting to check for **strict property name** and display an alert when the user is typing bad css properties. For example, typing "dislpay: none;" will throw an error because the property name "dislpay" doesn't exists, its "display".

**Comment by jwilsson** [comment]
Hi!
Thanks for the suggestion! 

However, since this would require a huge amount of data (to know which values are valid for which property etc.) I think this is a better fit for a [custom linter](https://github.com/lesshint/lesshint/blob/master/docs/developer-guide/linters.md) because it feels a bit on the heavy side to just pull that in for one rule.

If you decide to create a custom linter, send us a PR with a link to it and we'll be happy to add it to our README.

**Comment by xavierfoucrier** [comment]
Hi  @jwilsson!

I will try and take time to build a custom linter and send you a pull request when I would be less busy. Thanks for your answer.

Best regards!

**Comment by jwilsson** [comment]
@xavierfoucrier Awesome! Let me know if you need anything else.

Closing this for now.
