### ISSUE TITLE
PropertyValue support

### ISSUE THREAD

**Issue by xavierfoucrier** [lesshint/lesshint#463]
Add the ability to support `PropertyValue` setting to check for **strict property value** and display an alert when the user is typing bad css property values. For example, typing "display: 3px solid red;" will throw an error because the property named "display" doesn't contains the value "3px solid red;", its "none" / "block" / etc..

**Comment by jwilsson** [comment]
Hi!
Thanks for the suggestion! 

However, since this would require a huge amount of data (to know which values are valid for which property etc.) I think this is a better fit for a [custom linter](https://github.com/lesshint/lesshint/blob/master/docs/developer-guide/linters.md) because it feels a bit on the heavy side to just pull that in for one rule.

If you decide to create a custom linter, send us a PR with a link to it and we'll be happy to add it to our README.

**Comment by xavierfoucrier** [comment]
Hi  @jwilsson!

I will try and take time to build a custom linter and send you a pull request when I would be less busy. Thanks for your answer.

Best regards!

**Comment by jwilsson** [comment]
@xavierfoucrier Awesome! Let me know if you need anything else.

Closing this for now.
