### ISSUE TITLE
Add test to make sure we don't miss any console.logs in tests

### ISSUE THREAD

**Issue by kokarn** [lesshint/lesshint#88]

**Comment by jwilsson** [comment]
I'm not sure I follow, the `console.log`s in 0756cba7f1ee68ce0a05c4d89862bf8ed474416d were just stray ones which I forgot to remove.

Are you thinking of some sort of JSHint/JSCS check for `console.log`s in tests?

**Comment by kokarn** [comment]
Yeah, that should work. 
As long as it stops them from showing up in the commited code where they shouldn't be :)

**Comment by CITguy** [comment]
For a project I work on, we use a script to be run on the git pre-commit hook, so that it won't allow you to commit if there are debugging statements still present in the code. The hook installs itself via an NPM postinstall. Here's a gist that might be useful: https://gist.github.com/CITguy/1138a1701b9ffbf4e091

**Comment by jwilsson** [comment]
@CITguy looks pretty nice, thanks for sharing!

I'll see if I can work something out.

**Comment by jwilsson** [comment]
We talked about using Gulp and running all our tests and linting through it, and I figured we can check for stray `console.log()`s there as well (that way it'll be automatically run together with `npm test`). 

We just need to make sure it doesn't abort the tests while developing something. I'll work something out tonight.

**Comment by shellscape** [comment]
:+1:
